apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-bear-deployment-recreate
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: animal-deploy
  replicas: 1 
  template: 
    metadata:
      labels:
        app: animal-deploy
    spec:
      containers:
      - name: animal-bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
