# All resources that need to be created need to be in templates directory
# helm install spring-music ./spring-music
# helm uninstall spring-music
# helm install spring-music ./spring-music --debug --dry-run
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  #dbname: "db-mysql"
  #dbtable: "music"
  #dbname: {{.Values.dbname}}
  #dbtable: {{.Values.dbtable}}
  dbname: {{.Values.database_test.dbname}}
  dbtable: {{.Values.database_test.dbtable}}
  image: {{.Values.pods.image}}:{{.Values.pods.tag}}

  