apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name}}-{{ .Chart.Version | replace "." "-"}}
            image: {{ .Values.image }}:{{ .Values.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - {{ .Values.command }}
          restartPolicy: OnFailure