apiVersion: v1
kind: Pod
metadata:
  name: spring-animals
spec:
  containers:
  - name: animals
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  - name: spring
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  volumes:
  - name: app-storage
    hostPath:
      # directory location on host
      path: /tmp/files
      # this field is optional
      type: DirectoryOrCreate
